config/routes.rb
Eviterra::Application.routes.draw do

  match 'pricer' => 'pricer#pricer', :as => :pricer
  match 'calendar' => 'pricer#calendar', :as => :calendar
  match 'pricer/validate' => 'pricer#validate', :as => :pricer_validate
  match 'pricer/pricer_benchmark' => 'pricer#pricer_benchmark', :as => :pricer_pricer_benchmark

  constraints subdomain: 'api' do
    root to: 'api_home#index'
    match 'avia/v1/variants(.:format)' => 'pricer#api', :format => :xml
    match 'avia/v1/searches' => 'booking#api_redirect'
    match 'partner/v1/orders(.:format)' => 'api_order_stats#index', :format => :json
    match '*anything' => redirect('/')
  end

  match 'api/search(.:format)' => 'pricer#api', :format => :xml
  match 'api/redirection(.:format)' => 'booking#api_redirect'
  match 'api/booking/:query_key(.:format)' => 'booking#api_booking', :via => :get
  match 'api/rambler_booking(.:format)' => 'booking#api_rambler_booking', :via => :get, :format => :xml, :as => :api_rambler_booking
  match 'api/form' => 'booking#api_form'
  match 'api/order_stats' => 'api_order_stats#index'

  match 'booking' => 'booking#index', :as => :booking
  match 'hot_offers' => 'pricer#hot_offers', :as => :hot_offers
  match 'price_map' => 'pricer#price_map', :as => :price_map
  match 'booking/form' => 'booking#form', :as => :booking_form
  post 'booking/recalculate_price' => 'booking#recalculate_price', :as => :booking_recalculate_price
  post 'booking/pay' => 'booking#pay', :as => :booking_pay
  post 'api/pay' => 'api_booking#pay', :as => :api_booking_pay
  match 'booking/preliminary_booking' => 'booking#preliminary_booking', :as => :preliminary_booking
  match 'api/preliminary_booking' => 'api_booking#preliminary_booking', :as => :api_preliminary_booking
  post 'confirm_3ds' => 'booking#confirm_3ds', :as => :confirm_3ds
  match 'order/:id' => 'PNR#show', :as => :show_order
  match 'notice/:id' => 'PNR#show_notice', :as => :show_notice
  match 'order/:id/booked' => 'PNR#show_as_booked', :as => :show_booked_order
  match 'order/:id/order' => 'PNR#show_as_order', :as => :show_order_order
  match 'order/:id/ticketed' => 'PNR#show_as_ticketed', :as => :show_ticketed_order
  match 'order/:id/for_ticket/:ticket_id' => 'PNR#show_for_ticket', :as => :show_order_for_ticket
  match 'order/:id/receipt' => 'PNR#receipt', :as => :show_order_receipt
  match '/pay/:code(/:gateway)' => 'payments#edit', :via => :get, :as => :edit_payment
  match '/pay/:code(/:gateway)' => 'payments#update', :via => :post, :as => :edit_payment

  match '/corporate/start' => 'corporate#start', :as => :start_corporate
  match '/corporate/stop' => 'corporate#stop', :as => :stop_corporate
  match '/corporate' => 'corporate#index', :as => :corporate
  match '/flight_groups/:id' => 'flight_groups#show', :as => :show_flight_group
  match '/seat_map/:flight(/:booking_class)' => 'seat_map#show', :as => :show_seat_map

  resources :geo_tags

  match 'complete.json' => 'complete#complete'

  match 'about' => 'about#index', :as => :about
  match 'iata' => 'about#iata', :as => :about
  match 'faq' => 'about#faq', :as => :about
  match 'agreement' => 'about#agreement', :as => :about
  match 'agreement/old' => 'about#agreement_old', :as => :about
  match 'contacts' => 'about#contacts', :as => :about
  match 'about/:action' => 'about', :as => :about

  match "whereami" => 'home#whereami', :as => :whereami
  match "subscribe" => 'subscription#subscribe', :as => 'subscribe'
  match "unsubscribe" => 'subscription#unsubscribe', :as => 'unsubscribe'
  match "unsubscribe/:destination_id" => 'subscription#unsubscribe_by_destination', :as => 'unsubscribe_by_destination'

  match "admin/commissions/check" => 'admin/commissions#check', :as => 'check_admin_commissions'
  match "admin/commissions/table" => 'admin/commissions#table', :as => 'table_admin_commissions'
  match "admin/commissions" => 'admin/commissions#index', :as => 'admin_commissions'
  match "admin/new_hot_offers" => 'admin/hot_offers#best_of_the_week', :as => 'show_best_offers'
  match 'admin/notifications/show_sent_notice/:id' => 'admin/notifications#show_sent_notice', :as => :show_sent_notice
  match 'admin/reports/selling' => 'admin/reports#selling', :as => :admin_reports_selling

  root :to => 'home#index'

end

app/controllers/admin/orders_controller.rb
# encoding: utf-8
class Admin::OrdersController < Admin::EviterraResourceController
  include CustomCSV
  include Typus::Controller::Bulk

  before_filter :find_order, :only => [:show_pnr, :unblock, :charge, :money_received, :no_money_received, :ticket, :cancel, :reload_tickets, :update, :pnr_raw, :void, :make_payable_by_card, :send_invoice, :ticket_in_ticketing_office, :manual_notice]

  # def set_scope
  #   # добавлять фильтры лучше в def index и т.п., но так тоже работает (пока?)
  #   # Title, url, scope (можно пропустить, не будет счета)
  #   add_predefined_filter 'Unticketed', {:scope => 'unticketed'}, 'unticketed'
  #   add_predefined_filter 'Ticketed', {:scope => 'ticketed'}, 'ticketed'
  #   scope = params[:scope]
  #  if %W[unticketed ticketed].include?(scope)
  #    @resource = @resource.send(scope)
  #  end
  # end

  def index
    # так тоже можно. просто выставляет параметры обычных фильтров
    add_predefined_filter 'Unticketed', Order.unticketed.scope_attributes, 'unticketed'
    add_predefined_filter 'Processing Ticket', Order.processing_ticket.scope_attributes, 'processing_ticket'
    add_predefined_filter 'Error Ticket', Order.error_ticket.scope_attributes, 'error_ticket'
    add_predefined_filter 'Ticket Not Sent', {:scope => 'ticket_not_sent'}, 'ticket_not_sent'
    add_predefined_filter 'Sent Manual', Order.sent_manual.scope_attributes, 'sent_manual'
    add_predefined_filter 'MOWR228FA', {:scope => 'MOWR228FA'}
    add_predefined_filter 'MOWR2233B', {:scope => 'MOWR2233B'}
    add_predefined_filter 'MOWR221F9', {:scope => 'MOWR221F9'}
    add_predefined_filter 'MOWR2219U', {:scope => 'MOWR2219U'}
    add_predefined_filter 'FLL1S212V', {:scope => 'FLL1S212V'}
    # FIXME для наших дейт-фильтров нужен формат 2012/2/21 вместо 2012-02-21
    #add_predefined_filter 'Today', {:created_at => Date.today.to_s(:db)}
    #add_predefined_filter 'Yesterday', {:created_at => Date.yesterday.to_s(:db)}
    super
  end

  # FIXME копипаста из тайпуса, чтобы добавить вызов set_attributes_on_new.
  # надеюсь, в будущих версиях тайпуса - выковыряем
  def new
    @item = @resource.new(params[:resource])

    set_attributes_on_new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  def show_versions
    get_object
  end

  def show_pnr
    notice = {}
    notice[:id] = @order.pnr_number
    notice[:format] = params[:format] if params[:format]
    notice[:lang] = "en" if params[:lang]
    redirect_to show_notice_path(notice)
  end

  def pnr_raw
    render :text => @order.raw
  end

  def send_invoice
    InvoiceMailer.notice(@order.id, params[:comment]).deliver
    respond_to do |format|
      format.html { render :nothing => true }
      format.js   { render :nothing => true }
    end
  end

  def unblock
    if @order.unblock!
      flash[:notice] = 'Деньги разблокированы'
    else
      flash[:alert] = "Произошла ошибка"
    end
    redirect_to :action => :show, :id => @order.id
  end

  def charge
    if @order.charge!
      flash[:notice] = 'Деньги списаны с карты'
    else
      flash[:alert] = "Произошла ошибка"
    end
    redirect_to :action => :show, :id => @order.id
  end

  def money_received
    @order.money_received!
    redirect_to :controller => 'admin/payments', :action => :edit, :id => @order.last_payment.id
  end

  def no_money_received
    @order.no_money_received!
    redirect_to :action => :show, :id => @order.id
  end

  def make_payable_by_card
    @order.make_payable_by_card
    redirect_to :action => :show, :id => @order.id
  end

  def ticket
    flash[:alert] = 'не удалось загрузить все билеты' unless @order.ticket!
    redirect_to :action => :show, :id => @order.id
  end

  def cancel
    # может упасть и не изменить статус?
    @order.strategy.cancel
    redirect_to :action => :show, :id => @order.id
  end

  def reload_tickets
    @order.reload_tickets
    redirect_to :action => :show, :id => @order.id
  end

  def manual_notice
    @order.email_manual!
    redirect_to :action => :show, :id => @order.id
  end

  def ticket_in_ticketing_office
    @order.strategy.ticket
    if @order.ticket!
      flash[:notice] = 'Билеты загружены'
    else
      LoadTicketsJob.new(:order_id => @order.id).delay
      flash[:notice] = 'Билеты в процессе выписки. Они будут загружены в ближайшее время'
    end
    redirect_to :action => :show, :id => @order.id
  rescue Strategy::TicketError => e
    flash[:alert] = e.message.presence || 'Странная ошибка. Скажите, если случится.'
    redirect_to :action => :show, :id => @order.id
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def void
    @order.strategy.void
    redirect_to :action => :show, :id => @order.id
  end

  private

  def set_bulk_action
    add_bulk_action("Charge", "bulk_charge")
  end

  def bulk_charge(ids)
    ids.each { |id| @resource.find(id).charge! }
    notice = Typus::I18n.t("Tried to charge #{ids.count} entries. Probably successfully")
    redirect_to :back, :notice => notice
  end

  def set_attributes_on_new
    @item.offline_booking = true
  end
end

app/helpers/admin/orders_helper.rb
# encoding: utf-8
module Admin::OrdersHelper
end

app/views/admin/orders/_index.html.erb
<script type="text/javascript">
 jQuery(document).ready(function() {
   jQuery.timeago.settings.allowFuture = true;
   jQuery("abbr.timeago").timeago();
 });
</script>

<script type="text/javascript">
jQuery(function($) {
//  $("#sidebar").append($(".predefined_filters").html());
  $(".predefined_filters").first().clone().appendTo('#sidebar').wrap('<ul />');
  $("#sidebar .predefined_filters").css({border: '1px solid lightGrey', marginTop: '25px', lineHeight: '1.4', fontSize: '1.1em', color: '#444'});
  $("#sidebar .predefined_filters li").css({display: 'block'});
});
</script>


<%= render 'admin/resources/index' %>
(в выборке <%= @resource.count %> записей;
всего <%= number_to_currency @resource.sum(:price_with_payment_commission), :locale => :ru %> /
в среднем <%= number_to_currency @resource.average(:price_with_payment_commission), :locale => :ru %>)
<br />
Доход(income): <%= number_to_currency @resource.sum(:stored_income), :locale => :ru %>

app/views/admin/orders/_show.html.erb
<p style="text-align:right"><a href='/admin/orders/show_versions/<%=@item.id %>?_popup=true' class='iframe'>История изменений</a>
 | <a href="#" onclick="$('#send_invoice_form').toggle();return false">Invoice</a></p>

 <script type="text/javascript">
 jQuery(function($) {
   $("#send_invoice_form").bind("ajax:success", function(data, status, xhr) {
     $(this).fadeOut();
   });
 });
 </script>

 <div id="send_invoice_form" style="display: none; text-align:right">
 <%= form_tag url_for(:action => 'send_invoice', :id => @item.id), :method => :post, :remote => true do %>
 Комментарий: <%= text_field_tag :comment %>
 <%= submit_tag "Send", :class => :submit %>
 <% end %>
 </div>

<div id="term">Терминал:
  <pre data-replace-with="<%= url_for :action => :pnr_raw, :id => @item.id %>"></pre>
</div>

<div id="contentmenu"><ul>
  <li><%= link_to 'Показать PNR', {:action => 'show_pnr', :id => @item.id} %> / <%= link_to 'Show PNR', {:action => 'show_pnr', :id => @item.id, :lang => "en"} %></li>
  <li><%= link_to 'Бронирование', {:action => 'show_pnr', :id => @item.id, :format => 'booking'} %> / <%= link_to 'Booking', {:action => 'show_pnr', :id => @item.id, :format => 'booking', :lang => "en"} %></li>
  <li><%= link_to 'Заказ', {:action => 'show_pnr', :id => @item.id, :format => 'order'} %> / <%= link_to 'Order', {:action => 'show_pnr', :id => @item.id, :format => 'order', :lang => "en"} %></li>
  <li><%= link_to 'Билет', {:action => 'show_pnr', :id => @item.id, :format => 'ticket'} %> / <%= link_to 'Ticket', {:action => 'show_pnr', :id => @item.id, :format => 'ticket', :lang => "en"} %></li>
</ul></div>
<p></p>
<div>
    статус платежа: <strong><%= @item.payment_status %></strong> /
    статус билетов: <strong><%= @item.ticket_status %></strong> / 
    статус письма: <strong><%= @item.email_status %></strong> <% if @item.email_status != 'manual' %>[<%= link_to 'Переключить в Ручной режим', {:action => 'manual_notice', :id => @item.id}, {:confirm => 'Включить ручной режим оповещений?'} %>]<% end %>
    <br>
    <br>
</div>
<% if @item.code && @item.payment_status == 'not blocked' && @item.offline_booking? %>
<div id="pay_url">
URL для оплаты: <%= link_to edit_payment_url(:code => @item.code), edit_payment_url(:code => @item.code)%>
<% if @item.last_pay_time.try(:future?) %>
  действительна до <%= @item.last_pay_time.strftime("%d %b %Y, %H:%M") %>
<% else %>
  уже не действительна
<% end %>
</div>
<% end %>

<table><tr>
<% if @item.payment_status == 'blocked'  %>
  <td><%= button_to 'Charge', {:action => 'charge', :id => @item.id}, {:confirm => 'Списать деньги с карты? (возврат до двух месяцев!)'} %></td>
  <td><%= button_to 'Unblock', {:action => 'unblock', :id => @item.id}, {:confirm => 'разблокировать средства? (заблокировать их обратно уже не выйдет!)'} %></td>
<% end %>
<% if @item.payment_status == 'pending' %>
  <td><%= button_to 'Money received', {:action => 'money_received', :id => @item.id} %></td>
  <td><%= button_to 'No money received', {:action => 'no_money_received', :id => @item.id} %></td>
  <td><%= button_to 'дать оплатить картой', {:action => 'make_payable_by_card', :id => @item.id} %></td>
<% end %>
<% if ['booked', 'processing_ticket', 'error_ticket'].include? @item.ticket_status %>
  <td><%= button_to 'Ticket', {:action => 'ticket', :id => @item.id}, {:confirm => 'сменить состояние на "ticketed"? (реальная выписка пока делается из терминала)'}%></td>
  <% if @item.source == 'amadeus' && @item.ticket_status == 'booked' %>
  <td><%= button_to 'Выписать (экспериментально)', {:action => 'ticket_in_ticketing_office', :id => @item.id}, {:confirm => "Экспериментальная выписка в офисе #{@item.commission_ticketing_method}"}%></td>
  <% end %>
<% end %>
<% if @item.ticket_status == 'ticketed' && @item.source == 'sirena' %>
  <td><%= button_to 'Void', {:action => 'void', :id => @item.id}, {:confirm => 'отменить выписку (работает только в сирене, не снимает места!) ?'} %></td>
<% end %>
<% unless @item.ticket_status == 'canceled'  %>
  <td><%= button_to 'Cancel', {:action => 'cancel', :id => @item.id}, {:confirm => 'отменить бронирование?'} %></td>
<% end %>
<% if @item.ticket_status == 'ticketed' %>
  <td><%= button_to 'Обновить билеты', {:action => 'reload_tickets', :id => @item.id} %></td>
<% end %>
</tr> </table>

app/views/admin/orders/show_versions.html.erb
<% content_for :main_grid do %>

<div id="term">
  Версии:
</div>

<table>
  <thead>
    <tr>
      <th>Дата</th>
      <th>Автор</th>
      <th>Изменения</th>
    </tr>
  </thead>
<% @order.versions.each do |version| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= I18n.l(version.created_at, :format => 'long') %></td>
    <td><%= version.whodunnit || '--' %></td>
    <td>
    <% version.changeset.each do |attribute, (before, after)| %>
      <strong><%= @resource.human_attribute_name(attribute) %></strong>:
      <%= before %> → <%= after %>
      <br><br>
    <% end %>
  </td>
<% end %>

<% end %>