config/routes.rb
Eviterra::Application.routes.draw do

  match 'pricer' => 'pricer#pricer', :as => :pricer
  match 'calendar' => 'pricer#calendar', :as => :calendar
  match 'pricer/validate' => 'pricer#validate', :as => :pricer_validate
  match 'pricer/pricer_benchmark' => 'pricer#pricer_benchmark', :as => :pricer_pricer_benchmark

  constraints subdomain: 'api' do
    root to: 'api_home#index'
    match 'avia/v1/variants(.:format)' => 'pricer#api', :format => :xml
    match 'avia/v1/searches' => 'booking#api_redirect'
    match 'partner/v1/orders(.:format)' => 'api_order_stats#index', :format => :json
    match '*anything' => redirect('/')
  end

  match 'api/search(.:format)' => 'pricer#api', :format => :xml
  match 'api/redirection(.:format)' => 'booking#api_redirect'
  match 'api/booking/:query_key(.:format)' => 'booking#api_booking', :via => :get
  match 'api/rambler_booking(.:format)' => 'booking#api_rambler_booking', :via => :get, :format => :xml, :as => :api_rambler_booking
  match 'api/form' => 'booking#api_form'
  match 'api/order_stats' => 'api_order_stats#index'

  match 'booking' => 'booking#index', :as => :booking
  match 'hot_offers' => 'pricer#hot_offers', :as => :hot_offers
  match 'price_map' => 'pricer#price_map', :as => :price_map
  match 'booking/form' => 'booking#form', :as => :booking_form
  post 'booking/recalculate_price' => 'booking#recalculate_price', :as => :booking_recalculate_price
  post 'booking/pay' => 'booking#pay', :as => :booking_pay
  post 'api/pay' => 'api_booking#pay', :as => :api_booking_pay
  match 'booking/preliminary_booking' => 'booking#preliminary_booking', :as => :preliminary_booking
  match 'api/preliminary_booking' => 'api_booking#preliminary_booking', :as => :api_preliminary_booking
  post 'confirm_3ds' => 'booking#confirm_3ds', :as => :confirm_3ds
  match 'order/:id' => 'PNR#show', :as => :show_order
  match 'notice/:id' => 'PNR#show_notice', :as => :show_notice
  match 'order/:id/booked' => 'PNR#show_as_booked', :as => :show_booked_order
  match 'order/:id/order' => 'PNR#show_as_order', :as => :show_order_order
  match 'order/:id/ticketed' => 'PNR#show_as_ticketed', :as => :show_ticketed_order
  match 'order/:id/for_ticket/:ticket_id' => 'PNR#show_for_ticket', :as => :show_order_for_ticket
  match 'order/:id/receipt' => 'PNR#receipt', :as => :show_order_receipt
  match '/pay/:code(/:gateway)' => 'payments#edit', :via => :get, :as => :edit_payment
  match '/pay/:code(/:gateway)' => 'payments#update', :via => :post, :as => :edit_payment

  match '/corporate/start' => 'corporate#start', :as => :start_corporate
  match '/corporate/stop' => 'corporate#stop', :as => :stop_corporate
  match '/corporate' => 'corporate#index', :as => :corporate
  match '/flight_groups/:id' => 'flight_groups#show', :as => :show_flight_group
  match '/seat_map/:flight(/:booking_class)' => 'seat_map#show', :as => :show_seat_map

  resources :geo_tags

  match 'complete.json' => 'complete#complete'

  match 'about' => 'about#index', :as => :about
  match 'iata' => 'about#iata', :as => :about
  match 'faq' => 'about#faq', :as => :about
  match 'agreement' => 'about#agreement', :as => :about
  match 'agreement/old' => 'about#agreement_old', :as => :about
  match 'contacts' => 'about#contacts', :as => :about
  match 'about/:action' => 'about', :as => :about

  match "whereami" => 'home#whereami', :as => :whereami
  match "subscribe" => 'subscription#subscribe', :as => 'subscribe'
  match "unsubscribe" => 'subscription#unsubscribe', :as => 'unsubscribe'
  match "unsubscribe/:destination_id" => 'subscription#unsubscribe_by_destination', :as => 'unsubscribe_by_destination'

  match "admin/commissions/check" => 'admin/commissions#check', :as => 'check_admin_commissions'
  match "admin/commissions/table" => 'admin/commissions#table', :as => 'table_admin_commissions'
  match "admin/commissions" => 'admin/commissions#index', :as => 'admin_commissions'
  match "admin/new_hot_offers" => 'admin/hot_offers#best_of_the_week', :as => 'show_best_offers'
  match 'admin/notifications/show_sent_notice/:id' => 'admin/notifications#show_sent_notice', :as => :show_sent_notice
  match 'admin/reports/selling' => 'admin/reports#selling', :as => :admin_reports_selling

  root :to => 'home#index'

end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController

  before_filter :save_partner_cookies, :only => :index

  def index
  end

  def whereami
    loc = GeoIp.geolocation(request.remote_ip)
    render :json => {:city_name => nearest_city.name, :lat => loc[:latitude], :lng => loc[:longitude]}
  end

  protected

  # naive geolocation
  def nearest_city
    return Location.default unless Conf.geolocation.enabled
    @nearest_city ||= begin
      Timeout.timeout(1) do
        loc = GeoIp.geolocation(request.remote_ip)
        if loc[:latitude] == "0" && loc[:longitude] == "0" ||
          loc[:latitude] == "60" && loc[:longitude] == "100"
          return Location.default
        end
        City.nearest_to loc[:latitude], loc[:longitude]
      end
    # для оффлайна
    rescue Errno::EHOSTUNREACH, SocketError, JSON::ParserError, Timeout::Error, RestClient::Exception
      Location.default
    end
  end
  helper_method :nearest_city

end

app/views/home/_debug.html.erb
<% if admin_user %>
<div id="search-debug">
    Amadeus: <%= debug_service_env(:amadeus)%> <br>
    Сирена:  <%= debug_service_env(:sirena) %> <br>
    Payture: <%= debug_service_env(:payture) %><br>
    Payu: <%= debug_service_env(:payu) %><br>
    card processing: <%= Conf.payment.card_processing %>
</div>
<% end %>

app/views/home/_offers.html.erb
<div id="offers" class="clear g-none">

    <!-- Человекочитаемая строка запроса -->
    <div class="placeholder">
    <div id="offers-title">
        <h1>Из Москвы в Париж</h1>
        <div class="shadow"></div>
    </div>
    </div>

    <!-- Панель ожидания результатов -->
    <div id="offers-loading" class="offers-message g-none">
        <div class="om-photo">
            <p>Вы всегда можете проконсультироваться по&nbsp;всем вопросам или&nbsp;сделать заказ по&nbsp;телефону <strong><nobr>+7 495 660-35-20</nobr></strong> или&nbsp;по&nbsp;почте <a href="mailto:ticket@eviterra.com">ticket@eviterra.com</a></p>
        </div>
        <div class="om-text">
            <div class="progress"><span class="timer">0.0</span></div>
            <h3>Ищем для вас лучшие предложения</h3>
        </div>
    </div>

    <!-- Ничего не найдено -->
    <div id="offers-empty" class="offers-message g-none">
        <div class="om-photo">
            <p>Вы всегда можете проконсультироваться по&nbsp;всем вопросам или&nbsp;сделать заказ по&nbsp;телефону <strong><nobr>+7 495 660-35-20</nobr></strong> или&nbsp;по&nbsp;почте <a href="mailto:ticket@eviterra.com">ticket@eviterra.com</a></p>
        </div>
        <div class="om-text">
            <h3>Мы не смогли ничего найти :(</h3>
            <p>Попробуйте упростить маршрут или поискать другие даты</p>
        </div>
    </div>

    <!-- Результаты поиска -->
    <div id="offers-results" class="g-none">
    
        <!-- Только другие даты -->
        <div id="offers-imprecise" class="g-none">
            <p>Мы не смогли ничего найти в выбранные дни, но есть предложения на другие даты</p>
        </div>
        
        <!-- Фильтр результатов -->
        <div id="offers-filter">
        <div class="placeholder">
            <div id="offers-filter-content">
            <div class="of-collapsed">
                <span class="link reset-filters g-none">Все варианты</span>
                <span class="link expand-filters">Уточнить</span> количество пересадок, время, аэропорты и прочее
            </div>
            <table class="of-expanded">
            <tr>
                <th>
                    <span id="offers-empty-filters">Уточнить</span>
                    <a href="#" class="g-none reset-filters">Все&nbsp;варианты</a>
                </th>
                <td rowspan="2">
                    <h5>Пересадки</h5>
                    <div class="filters">
                        <div class="filter" id="layovers-filter" data-name="layovers"><span class="control">количество и длительность пересадок</span><span class="values"></span><div class="dropdown"><dl><dt>количество пересадок</dt><dd class="empty">всё равно</dd></dl></div></div>
                        <div class="filter" data-name="cities"><span class="control">город пересадки</span><span class="values">…</span><div class="dropdown"><dl><dt>город пересадки</dt><dd class="empty">любой</dd></dl></div></div>
                    </div>
                </td>
                <td rowspan="2">
                    <h5>Время</h5>
                    <div class="filters">
                        <div class="filter" data-name="dpt_time_0" data-location="dpt_0"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>время вылета</dt><dd class="empty">любое</dd></dl></div></div>
                        <div class="filter" data-name="arv_time_0" data-location="arv_0"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>время прилёта</dt><dd class="empty">любое</dd></dl></div></div>
                        <div class="filter" data-name="dpt_time_1" data-location="dpt_1"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>время вылета</dt><dd class="empty">любое</dd></dl></div></div>
                        <div class="filter" data-name="arv_time_1" data-location="arv_1"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>время прилёта</dt><dd class="empty">любое</dd></dl></div></div>
                        <div class="filter" data-name="dpt_time_2" data-location="dpt_2"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>время вылета</dt><dd class="empty">любое</dd></dl></div></div>
                        <div class="filter" data-name="arv_time_2" data-location="arv_2"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>время прилёта</dt><dd class="empty">любое</dd></dl></div></div>
                    </div>
                </td>
                <td rowspan="2">
                    <h5>Аэропорты</h5>
                    <div class="filters">
                        <div class="filter" data-name="dpt_city_0" data-location="dpt_0"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>город вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="dpt_airport_0" data-location="dpt_0"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_city_0" data-location="arv_0"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>город прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_airport_0" data-location="arv_0"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="dpt_city_1" data-location="dpt_1"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>город вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="dpt_airport_1" data-location="dpt_1"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_city_1" data-location="arv_1"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>город прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_airport_1" data-location="arv_1"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="dpt_city_2" data-location="dpt_2"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>город вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="dpt_airport_2" data-location="dpt_2"><span class="control">вылет</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт вылета</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_city_2" data-location="arv_2"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>город прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                        <div class="filter" data-name="arv_airport_2" data-location="arv_2"><span class="control">прилёт</span><span class="values">…</span><div class="dropdown"><dl><dt>аэропорт прилёта</dt><dd class="empty">любой</dd></dl></div></div>
                    </div>
                </td>
                <td rowspan="2">
                    <h5>Другие детали</h5>
                    <div class="filters">
                        <div class="filter" data-name="carriers"><span class="control">авиакомпания</span><span class="values">…</span><div class="dropdown"><dl><dt>авиакомпания</dt><dd class="empty">любая</dd></dl></div></div>                
                        <div class="filter" data-name="planes"><span class="control">самолёт</span><span class="values">…</span><div class="dropdown"><dl><dt>самолёт</dt><dd class="empty">любой</dd></dl></div></div>
                    </div>
                </td>
            </tr>
            <tr>
                <th class="collapse-container">
                    <span class="collapse-filters">Свернуть &uarr;</span>
                </th>
            </tr>
            </table>
            <div class="shadow"></div>
            </div>
        </div>
        </div>

        <!-- Вкладки списка результатов -->
        <div id="offers-tabs">
            <ul>
                <li id="offers-tab-featured" class="active"><a href="#" onclick="return {v: 'featured'}">Мы рекомендуем</a></li>
                <li id="offers-tab-all"><a href="#" onclick="return {v: 'all'}">Всего 42 варианта</a></li>
                <li id="offers-tab-matrix"><a href="#" onclick="return {v: 'matrix'}">&plusmn; 3 дня</a></li>
            </ul>
        </div>
        <div id="offers-content">

        <!-- Список результатов -->
        <div id="offers-list">
        <div id="offers-featured" class="g-none"></div>
        <div id="offers-matrix" class="g-none">
            <div class="offer">
                <table class="offer-prices">
                <col width="120">
                <col width="*" span="7">
                <tr>
                    <th class="direction"><h6 class="segment1">Туда</h6><h6 class="segment2">Обратно</h6></th>
                    <th class="first"></th><th></th><th></th><th></th><th></th><th></th><th class="last"></th>
                </tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                <tr class="diffret"><th class="ret"></th><td></td><td></td><td></td><td></td><td></td><td></td><td class="last"></td></tr>
                </table>
                <div id="offers-mcollection"></div>
            </div>
        </div>
        <div id="offers-all" class="offers g-none">
            <div class="offers-sort">
                <h3 class="offers-title">Все варианты, отсортированные <span id="offers-sortedby">по цене</span></h3>
                <p>можно 
                    <a href="#" class="sortedby" onclick="return 'price'">по цене</a>,
                    <a href="#" onclick="return 'duration'">по времени в пути</a>,
                    <a href="#" onclick="return 'departures'">по времени вылета</a>
                    или&nbsp;<a href="#" onclick="return 'carrier'">по авиакомпании</a>
                </p>
            </div>
            <div class="offers-improper offers-message g-none">
                <div class="om-photo"><br></div>
                <div class="om-text">
                    <h3>Таких вариантов нет</h3>
                    <p>Нужно сбросить один или <span class="link reset-filters">все фильтры</span></p>
                </div>
            </div>
            <div id="offers-pcollection"></div>
        </div>
        </div>
        <!-- /Список результатов -->
        
        </div>
    </div>
    
</div>

app/views/home/_results.html.erb
<div id="results-header">
<div class="rh-wrapper">
    <table class="rh-content">
    <tr>
        <td class="rh-left"><h3 class="rh-summary"></h3></td>
        <td class="rh-right">
            <div id="results-button">
                <div class="rb-side rb-disabled"><div class="rb-side">Найти&nbsp;билеты</div></div>
                <div class="rb-side rb-enabled"><div class="rb-side"><div class="rb-active">Найти&nbsp;билеты</div></div></div>
            </div>
            <div class="rh-edit"><span class="rhe-link">Новый&nbsp;поиск</span></div>
            <div class="rh-select"><span class="rhs-link">Все&nbsp;варианты перелета</span></div>            
        </td>
    </tr>
    </table>
    <div id="results-filters">
        <div class="rf-group" data-id="time">
            <div class="rfg-control"><span class="rfg-label">Время вылета и прилета</span><span class="rfg-counter"></span></div>
            <div class="rfg-content"></div>
        </div>
        <div class="rf-group" data-id="locations">
            <div class="rfg-control"><span class="rfg-label">Города и аэропорты</span><span class="rfg-counter"></span></div>
            <div class="rfg-content"></div>
        </div>
        <div class="rf-group" data-id="carriers">
            <div class="rfg-control"><span class="rfg-label">Авиакомпании и самолеты</span><span class="rfg-counter"></span></div>
            <div class="rfg-content"></div>
        </div>
        <div class="rf-group" data-id="layovers">
            <div class="rfg-control"><span class="rfg-label">Пересадки</span><span class="rfg-counter"></span></div>
            <div class="rfg-content"></div>
        </div>                        
    </div>
    <div class="rh-shadow"></div>
</div>
</div>

<div id="results-message">
<div class="rm-half"></div>
<div class="rm-content">
    <div id="rm-loading">
        <h3 class="rm-title"><span class="rmt-text">Ищем для вас лучшие предложения</span></h3>
        <h6 class="rml-progress">Это займет от пяти до тридцати секунд</h6>
        <ul class="rml-features">
            <li>Поиск осуществляется по предложениям около 500 авиакомпаний</li>
            <li style="display: none;">Средняя цена на этом направлении — 14800 рублей за билет на одного человека.</li>
            <li>Цены будут показаны в рублях</li>
            <li>Можно будет сразу оплатить банковской картой Visa или MasterCard</li>
        </ul>
        <div class="rml-advice">
            <p><strong class="rmla-prefix">Совет:</strong> чем раньше от&nbsp;момента вылета вы&nbsp;покупаете авиабилеты, тем&nbsp;они, как&nbsp;правило, дешевле.</p>
        </div>
        <p class="appstore" style="margin-top: 15px;"><a target="_blank" href="https://itunes.apple.com/ru/app/eviterra/id569307779?mt=8&uo=4"><img alt "Available in App Store" src="images/common/appstore-available.png" /></a></p>
    </div>
    <div id="rm-empty">
        <h3 class="rm-title">Мы не смогли ничего найти :-(</h3>
        <h6 class="rme-title">Возможные причины:</h6>
        <ul class="rme-reasons">
            <li>Нет перелетов именно в выбранные дни. Попробуйте указать другие даты</li>
            <li>У нас не представлены авиакомпании, выполняющие рейсы на этом направлении. Мы постоянно подключаем новые, попробуйте проверить искомое направление позже</li>
            <li>На этом маршруте не существует регулярного авиасообщения. Попробуйте выбрать другой город</li>
        </ul>
    </div>
</div>
</div>

<div id="results-content">

    <div id="results-tabs">
    <div id="rf-placeholder"></div>
    <ul class="rt-content wrap">
        <li class="rt-item" data-tab="cheap">Дешевые</li>
        <li class="rt-item" data-tab="optimal">Оптимальные</li>
        <li class="rt-item" data-tab="nonstop">Прямые</li>
        <li class="rt-item" data-tab="all">Все</li>
        <li class="rt-item rt-matrix" data-tab="matrix">± 3 дня</li>
    </ul>
    </div>

    <div class="o-book" id="ob-template">
        <div class="ob-button">
            <div class="obb-title">Купить</div>
            <div class="obb-side obb-left"><div class="obb-side obb-right"></div></div>
        </div>
        <div class="od-control od-show">Показать подробности</div>
        <div class="od-control od-hide">Скрыть подробности</div>
        <div class="ob-state"></div>
        <div class="ob-line"></div>
    </div>
    
    <div id="ost-template">
    <ul class="os-title wrap">
        <li class="ost-item ost-name"><span class="ostn-text">{0}</span></li>
        <li class="ost-item ost-dpt">Вылет</li>
        <li class="ost-item ost-duration">В пути</li>
        <li class="ost-item ost-arv">Прибытие</li>
    </ul>
    </div>
    
    <div id="results-cheap" class="offers-list"></div>
    <div id="results-optimal" class="offers-list"></div>
    <div id="results-nonstop" class="offers-list"></div>    
    <div id="results-all" class="offers-list"></div>
    <div id="results-matrix" class="offers-list">
        <div class="offer">
        <div class="rm-prices">
        <table class="rmp-table">
            <tr><td class="rmpt-rt" style="background: none;"></td><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr><th class="rmpt-rt"></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            <tr class="rmpt-rt"><th></th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        </table>
        </div>
        </div>
    </div>
    
    <div class="rc-placeholder"></div>
    
</div>

app/views/home/index.html.erb
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
	<meta charset="utf-8">
    <title>Eviterra — самые дешевые авиабилеты по всему миру онлайн. Все авиакомпании. Максимальные скидки.</title>
    <meta name="description" content="Eviterra — простой, удобный и быстрый способ найти и купить авиабилет. Поиск, выбор рейса и бронирование онлайн. Мгновенная оплата и оформление авиабилетов. Цены на авиабилеты.">
    <meta name="keywords" content="авиабилет, авиабилеты, дешевые авиабилеты, авиабилеты онлайн, авиакасса, авиа билеты, авиакомпании, все авиакомпании, купить авиабилеты, куплю авиабилеты, авиабилеты дешево, самые дешевые авиабилеты, стоимость авиабилетов, билеты на самолет, авиабилеты из москвы, забронировать авиабилеты, бронирование авиабилетов, выбрать рейс, авиарейс, перелет, дешевые авиаперелеты, цены на билеты, онлайн бронирование, эвитерра, авитерра, авитера, евитерра, eviterra, aviterra.ru, evitera, эвитера, эвиттера, эвиттерра, спецпредложения, акции, авиакомпании, расписание рейсов, сложный маршрут, агентство, турагентство, путешествия, аэрофлот, трансаэро, lufthansa, iberia, s7, сибирь, delta, ютэйр, гтк россия, пулково, аэросвит, air berlin, шереметьево, домодедово, внуково, авиабилеты по россии, авиабилеты в европу, авиабилеты в сша">
    <%= render 'shared/head' %>
    <%= stylesheet_link_tag 'home' %>
    <%= javascript_include_tag "local/ru", 'home' %>
</head>
<body>

<%= render 'shared/header' %>
<%= render 'search' %>
<%= render 'results' %>

<% if corporate_mode? %>
    <div id="corporate">
    <div class="corporate-content">
        <a class="corporate-exit" href="<%= stop_corporate_url %>">Выйти</a>
        <p class="corporate-message">Вы находитесь в корпоративном режиме.</p>
    </div>
    </div>
<% end %>

<div id="booking">
    <div class="b-content offer"></div>
    <div class="b-loading">
        <h5 class="bl-title"><span class="bl-progress">Проверяем доступность мест</span><h5>
    </div>
</div>

<div id="queries">
<div class="q-content">
    <div class="q-history"></div>
    <div class="q-live">
        <h5 class="ql-title">Что находят и покупают:</h5>
        <ul class="ql-items"></ul>
    </div>
</div>
</div>

<div id="hint">
    <div class="h-close"></div>
    <div class="h-content"></div>
</div>

<%= render 'shared/footer' %>

<script type="text/javascript">
page.init();
</script>

<script src="//translate.google.com/translate_a/element.js?cb=googleSectionalElementInit&ug=section&hl=ru"></script>
<script type="text/javascript" src="https://maps-api-ssl.google.com/maps/api/js?v=3&sensor=false&language=ru"></script>

<script type="text/javascript" src="//vk.com/js/api/openapi.js?68"></script>
<script type="text/javascript">
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=429677207045748";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
(function(d, s, id) {
    var js,fjs=d.getElementsByTagName(s)[0];
    if(!d.getElementById(id)) {
        js = d.createElement(s); js.id = id;
        js.src="//platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);}
}(document,"script","twitter-wjs"));
(function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
(function() {
    VK.init({apiId: 3261549, onlyWidgets: true});
    VK.Widgets.Like('vk-like', {type: 'mini', height: 20, pageUrl: 'https://eviterra.com/'});
})();
$('#share-icons').show();
</script>

</body>
</html>